FACTION.name = "Citizens of America"
FACTION.desc = "Citizens."
FACTION.color = Color(127, 201, 255)
FACTION.isDefault = true
FACTION.models = {"models/project-new-york/winter/baseline_male06.mdl", "models/project-new-york/winter/baseline_male05.mdl", "models/project-new-york/winter/baseline_male04.mdl", "models/project-new-york/winter/baseline_male03.mdl", "models/project-new-york/winter/baseline_male02.mdl", "models/project-new-york/winter/baseline_male01.mdl",}
FACTION.pay = 50
FACTION.payTimer = 3600
FACTION.isGloballyRecognized = false
FACTION_CITIZEN = FACTION.index
