--------------------------------------------------------------------------------------------------------
FACTION.name = "Citizens of Berlin"
FACTION.desc = "The Citizens of Berlin."
FACTION.color = Color(51, 117, 232)
FACTION.isDefault = true
FACTION.pay = 5
FACTION.isGloballyRecognized = false
FACTION.models = {"models/prometheus/suits/male_02_closed_coat_tie.mdl", "models/prometheus/suits/male_02_closed_tie.mdl", "models/prometheus/suits/male_02_open.mdl", "models/prometheus/suits/male_02_open_tie.mdl", "models/prometheus/suits/male_02_open_waistcoat.mdl", "models/prometheus/suits/male_02_shirt.mdl", "models/prometheus/suits/male_02_shirt_tie.mdl", "models/prometheus/suits/male_04_closed_coat_tie.mdl", "models/prometheus/suits/male_04_closed_tie.mdl", "models/prometheus/suits/male_04_open.mdl", "models/prometheus/suits/male_04_open_tie.mdl", "models/prometheus/suits/male_04_open_waistcoat.mdl", "models/prometheus/suits/male_04_shirt.mdl", "models/prometheus/suits/male_04_shirt_tie.mdl", "models/prometheus/suits/male_05_closed_coat_tie.mdl", "models/prometheus/suits/male_05_closed_tie.mdl", "models/prometheus/suits/male_05_open.mdl", "models/prometheus/suits/male_02_open_tie.mdl", "models/prometheus/suits/male_05_open_waistcoat.mdl", "models/prometheus/suits/male_05_shirt.mdl", "models/prometheus/suits/male_05_shirt_tie.mdl", "models/prometheus/suits/male_06_closed_coat_tie.mdl", "models/prometheus/suits/male_06_closed_tie.mdl", "models/prometheus/suits/male_06_open.mdl", "models/prometheus/suits/male_06_open_tie.mdl", "models/prometheus/suits/male_06_open_waistcoat.mdl", "models/prometheus/suits/male_06_shirt.mdl", "models/prometheus/suits/male_06_shirt_tie.mdl", "models/prometheus/suits/male_07_closed_coat_tie.mdl", "models/prometheus/suits/male_07_closed_tie.mdl", "models/prometheus/suits/male_07_open.mdl", "models/prometheus/suits/male_07_open_tie.mdl", "models/prometheus/suits/male_07_open_waistcoat.mdl", "models/prometheus/suits/male_07_shirt.mdl", "models/prometheus/suits/male_07_shirt_tie.mdl", "models/prometheus/suits/male_08_closed_coat_tie.mdl", "models/prometheus/suits/male_08_closed_tie.mdl", "models/prometheus/suits/male_08_open.mdl", "models/prometheus/suits/male_08_open_tie.mdl", "models/prometheus/suits/male_08_open_waistcoat.mdl", "models/prometheus/suits/male_08_shirt.mdl", "models/prometheus/suits/male_08_shirt_tie.mdl", "models/prometheus/suits/male_09_closed_coat_tie.mdl", "models/prometheus/suits/male_09_closed_tie.mdl", "models/prometheus/suits/male_09_open.mdl", "models/prometheus/suits/male_09_open_tie.mdl", "models/prometheus/suits/male_09_open_waistcoat.mdl", "models/prometheus/suits/male_09_shirt.mdl", "models/prometheus/suits/male_09_shirt_tie.mdl", "models/prometheus/suits/male_10_closed_coat_tie.mdl", "models/prometheus/suits/male_10_open.mdl", "models/prometheus/suits/male_10_open_tie.mdl", "models/prometheus/suits/male_10_open_waistcoat.mdl", "models/prometheus/suits/male_10_shirt.mdl", "models/prometheus/suits/male_10_shirt_tie.mdl"
}
FACTION_CITIZEN = FACTION.index
--------------------------------------------------------------------------------------------------------