ITEM.name = "Black Velvet"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/black velvet/black velvet.mdl"
ITEM.uniqueID = "blackvelvet"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 30
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
