ITEM.name = "Bloody Mary"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/bloody mary/bloody mary.mdl"
ITEM.uniqueID = "bloodymary"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 40
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
