ITEM.name = "Brandy Fizz"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/brandy fizz/brandy fizz.mdl"
ITEM.uniqueID = "brandyfizz"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 20
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
