ITEM.name = "Cape Codder"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/cape codder/cape codder.mdl"
ITEM.uniqueID = "capecodder"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 40
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
