ITEM.name = "Cliquet"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/cliquet/cliquet.mdl"
ITEM.uniqueID = "cliquet"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 30
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
