ITEM.name = "Daquiri"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/daquiri/daquiri.mdl"
ITEM.uniqueID = "daquiri"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 40
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
