ITEM.name = "Death in the afternoon"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/death in the afternoon/death in the afternoon.mdl"
ITEM.uniqueID = "deathafternoon"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 40
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
