ITEM.name = "El Presidente"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/el presidente/el presidente.mdl"
ITEM.uniqueID = "el presidente"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 30
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
