ITEM.name = "Irish Coffee"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/irish coffee/irish coffee.mdl"
ITEM.uniqueID = "irishcoffee"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 25
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
