ITEM.name = "Jarate toddy"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/jarate toddy/jarate toddy.mdl"
ITEM.uniqueID = "jarate toddy"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 25
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
