ITEM.name = "Mimosa"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/mimosa/mimosa.mdl"
ITEM.uniqueID = "mimosa"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 20
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
