ITEM.name = "Martini"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/martini/martini.mdl"
ITEM.uniqueID = "martini"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 40
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
