ITEM.name = "Sano grog"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/sano grog/sano grog.mdl"
ITEM.uniqueID = "sanogrog"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 30
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
