ITEM.name = "Sidecar"
ITEM.desc = "An alchoholic Cocktail"
ITEM.model = "models/sidecar/sidecar.mdl"
ITEM.uniqueID = "sidecar"
ITEM.width = 1
ITEM.height = 1
ITEM.abv = 30
ITEM.desc = "Alchoholic Cocktail"
ITEM.sound = "eating_and_drinking/drinking.wav"
