MODULE.name = "Framework UI - F1 Menu"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "1.0"
MODULE.desc = "Adds a F1 Menu that allows to access several characters sub-menus."
