ITEM.name = "Springfield Model 1903"
ITEM.desc = "The Springfield Model 1903 is a bolt-action rifle chambered in .30-06 Springfield, developed by the Springfield Armory. Renowned for its accuracy, reliability, and robust construction, it served as the standard issue rifle for the U.S. military during the Great War."
ITEM.category = "Weapons"
ITEM.model = "models/weapons/arccw/w_waw_k98k.mdl"
ITEM.class = "arccw_waw_springfield"
ITEM.slot = "weapons"
ITEM.width = 6
ITEM.height = 2
ITEM.isWeapon = true
ITEM.weaponCategory = "primary"
